#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'maislurp-client-powershell' -name 'ApiAuditLogControllerApi' {
    Context 'Get-AuditLogByEventId' {
        It 'Test Get-AuditLogByEventId' {
            #$TestResult = Get-AuditLogByEventId -EventId "TEST_VALUE" -Since "TEST_VALUE" -Before "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-AuditLogs' {
        It 'Test Get-AuditLogs' {
            #$TestResult = Get-AuditLogs -Since "TEST_VALUE" -Before "TEST_VALUE" -Action "TEST_VALUE" -UserId "TEST_VALUE" -ActorUserId "TEST_VALUE" -TargetUserId "TEST_VALUE" -ResourceType "TEST_VALUE" -ResourceId "TEST_VALUE" -Outcome "TEST_VALUE" -RequestId "TEST_VALUE" -IpAddress "TEST_VALUE" -PageSize "TEST_VALUE" -Cursor "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Search-AuditLogs' {
        It 'Test Search-AuditLogs' {
            #$TestResult = Search-AuditLogs -AuditLogSearchOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
