#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'maislurp-client-powershell' -name 'ConnectorControllerApi' {
    Context 'New-Connector' {
        It 'Test New-Connector' {
            #$TestResult = New-Connector -CreateConnectorOptions "TEST_VALUE" -InboxId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-ConnectorImapConnection' {
        It 'Test New-ConnectorImapConnection' {
            #$TestResult = New-ConnectorImapConnection -Id "TEST_VALUE" -CreateConnectorImapConnectionOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-ConnectorSmtpConnection' {
        It 'Test New-ConnectorSmtpConnection' {
            #$TestResult = New-ConnectorSmtpConnection -Id "TEST_VALUE" -CreateConnectorSmtpConnectionOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-ConnectorSyncSettings' {
        It 'Test New-ConnectorSyncSettings' {
            #$TestResult = New-ConnectorSyncSettings -Id "TEST_VALUE" -CreateConnectorSyncSettingsOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-ConnectorWithOptions' {
        It 'Test New-ConnectorWithOptions' {
            #$TestResult = New-ConnectorWithOptions -CreateConnectorWithOptions "TEST_VALUE" -InboxId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteAllConnector' {
        It 'Test Invoke-DeleteAllConnector' {
            #$TestResult = Invoke-DeleteAllConnector
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteConnector' {
        It 'Test Invoke-DeleteConnector' {
            #$TestResult = Invoke-DeleteConnector -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteConnectorImapConnection' {
        It 'Test Invoke-DeleteConnectorImapConnection' {
            #$TestResult = Invoke-DeleteConnectorImapConnection -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteConnectorSmtpConnection' {
        It 'Test Invoke-DeleteConnectorSmtpConnection' {
            #$TestResult = Invoke-DeleteConnectorSmtpConnection -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteConnectorSyncSettings' {
        It 'Test Invoke-DeleteConnectorSyncSettings' {
            #$TestResult = Invoke-DeleteConnectorSyncSettings -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-AllConnectorEvents' {
        It 'Test Get-AllConnectorEvents' {
            #$TestResult = Get-AllConnectorEvents -Id "TEST_VALUE" -Page "TEST_VALUE" -Size "TEST_VALUE" -Sort "TEST_VALUE" -Since "TEST_VALUE" -Before "TEST_VALUE" -EventType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-Connector' {
        It 'Test Get-Connector' {
            #$TestResult = Get-Connector -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ConnectorByEmailAddress' {
        It 'Test Get-ConnectorByEmailAddress' {
            #$TestResult = Get-ConnectorByEmailAddress -EmailAddress "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ConnectorByInboxId' {
        It 'Test Get-ConnectorByInboxId' {
            #$TestResult = Get-ConnectorByInboxId -InboxId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ConnectorByName' {
        It 'Test Get-ConnectorByName' {
            #$TestResult = Get-ConnectorByName -Name "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ConnectorEvent' {
        It 'Test Get-ConnectorEvent' {
            #$TestResult = Get-ConnectorEvent -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ConnectorEvents' {
        It 'Test Get-ConnectorEvents' {
            #$TestResult = Get-ConnectorEvents -Id "TEST_VALUE" -Page "TEST_VALUE" -Size "TEST_VALUE" -Sort "TEST_VALUE" -Since "TEST_VALUE" -Before "TEST_VALUE" -EventType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ConnectorImapConnection' {
        It 'Test Get-ConnectorImapConnection' {
            #$TestResult = Get-ConnectorImapConnection -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ConnectorProviderSettings' {
        It 'Test Get-ConnectorProviderSettings' {
            #$TestResult = Get-ConnectorProviderSettings
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ConnectorSmtpConnection' {
        It 'Test Get-ConnectorSmtpConnection' {
            #$TestResult = Get-ConnectorSmtpConnection -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ConnectorSyncSettings' {
        It 'Test Get-ConnectorSyncSettings' {
            #$TestResult = Get-ConnectorSyncSettings -Id "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-Connectors' {
        It 'Test Get-Connectors' {
            #$TestResult = Get-Connectors -Page "TEST_VALUE" -Size "TEST_VALUE" -Sort "TEST_VALUE" -Since "TEST_VALUE" -Before "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Send-EmailFromConnector' {
        It 'Test Send-EmailFromConnector' {
            #$TestResult = Send-EmailFromConnector -Id "TEST_VALUE" -SendEmailOptions "TEST_VALUE" -UseFallback "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Sync-Connector' {
        It 'Test Sync-Connector' {
            #$TestResult = Sync-Connector -Id "TEST_VALUE" -Since "TEST_VALUE" -Folder "TEST_VALUE" -Logging "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Test-ConnectorImapConnection' {
        It 'Test Test-ConnectorImapConnection' {
            #$TestResult = Test-ConnectorImapConnection -Id "TEST_VALUE" -CreateConnectorImapConnectionOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Test-ConnectorImapConnectionOptions' {
        It 'Test Test-ConnectorImapConnectionOptions' {
            #$TestResult = Test-ConnectorImapConnectionOptions -CreateConnectorImapConnectionOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Test-ConnectorSmtpConnection' {
        It 'Test Test-ConnectorSmtpConnection' {
            #$TestResult = Test-ConnectorSmtpConnection -Id "TEST_VALUE" -CreateConnectorSmtpConnectionOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Test-ConnectorSmtpConnectionOptions' {
        It 'Test Test-ConnectorSmtpConnectionOptions' {
            #$TestResult = Test-ConnectorSmtpConnectionOptions -CreateConnectorSmtpConnectionOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-Connector' {
        It 'Test Update-Connector' {
            #$TestResult = Update-Connector -Id "TEST_VALUE" -CreateConnectorOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-ConnectorImapConnection' {
        It 'Test Update-ConnectorImapConnection' {
            #$TestResult = Update-ConnectorImapConnection -Id "TEST_VALUE" -CreateConnectorImapConnectionOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-ConnectorSmtpConnection' {
        It 'Test Update-ConnectorSmtpConnection' {
            #$TestResult = Update-ConnectorSmtpConnection -Id "TEST_VALUE" -CreateConnectorSmtpConnectionOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
