#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'maislurp-client-powershell' -name 'EmailAuditControllerApi' {
    Context 'Compare-EmailAudits' {
        It 'Test Compare-EmailAudits' {
            #$TestResult = Compare-EmailAudits -AuditId "TEST_VALUE" -OtherAuditId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-EmailAudit' {
        It 'Test New-EmailAudit' {
            #$TestResult = New-EmailAudit -CreateEmailAuditOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteEmailAudit' {
        It 'Test Invoke-DeleteEmailAudit' {
            #$TestResult = Invoke-DeleteEmailAudit -AuditId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-EmailAudit' {
        It 'Test Get-EmailAudit' {
            #$TestResult = Get-EmailAudit -AuditId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-EmailAudits' {
        It 'Test Get-EmailAudits' {
            #$TestResult = Get-EmailAudits -EmailId "TEST_VALUE" -Since "TEST_VALUE" -Before "TEST_VALUE" -Limit "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
