#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'maislurp-client-powershell' -name 'ToolsControllerApi' {
    Context 'New-BimiRecord' {
        It 'Test New-BimiRecord' {
            #$TestResult = New-BimiRecord -GenerateBimiRecordOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-DmarcRecord' {
        It 'Test New-DmarcRecord' {
            #$TestResult = New-DmarcRecord -GenerateDmarcRecordOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-MtaStsRecord' {
        It 'Test New-MtaStsRecord' {
            #$TestResult = New-MtaStsRecord -GenerateMtaStsRecordOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-TlsReportingRecord' {
        It 'Test New-TlsReportingRecord' {
            #$TestResult = New-TlsReportingRecord -GenerateTlsReportingRecordOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-LookupBimiDomain' {
        It 'Test Invoke-LookupBimiDomain' {
            #$TestResult = Invoke-LookupBimiDomain -LookupBimiDomainOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-LookupDmarcDomain' {
        It 'Test Invoke-LookupDmarcDomain' {
            #$TestResult = Invoke-LookupDmarcDomain -LookupDmarcDomainOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-LookupMtaStsDomain' {
        It 'Test Invoke-LookupMtaStsDomain' {
            #$TestResult = Invoke-LookupMtaStsDomain -LookupMtaStsDomainOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-LookupTlsReportingDomain' {
        It 'Test Invoke-LookupTlsReportingDomain' {
            #$TestResult = Invoke-LookupTlsReportingDomain -LookupTlsReportingDomainOptions "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
