#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Summary
No description available.
.PARAMETER ReceivedPath
No description available.
.PARAMETER ParsedHeaders
No description available.
.PARAMETER Warnings
No description available.
.PARAMETER Errors
No description available.
.OUTPUTS

AnalyzeEmailHeadersResults<PSCustomObject>
#>

function Initialize-AnalyzeEmailHeadersResults {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Summary},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ReceivedPath},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Collections.Hashtable]
        ${ParsedHeaders},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Warnings},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Errors}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => AnalyzeEmailHeadersResults' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Summary -eq $null) {
            throw "invalid value for 'Summary', 'Summary' cannot be null."
        }

        if ($ReceivedPath -eq $null) {
            throw "invalid value for 'ReceivedPath', 'ReceivedPath' cannot be null."
        }

        if ($ParsedHeaders -eq $null) {
            throw "invalid value for 'ParsedHeaders', 'ParsedHeaders' cannot be null."
        }

        if ($Warnings -eq $null) {
            throw "invalid value for 'Warnings', 'Warnings' cannot be null."
        }

        if ($Errors -eq $null) {
            throw "invalid value for 'Errors', 'Errors' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "summary" = ${Summary}
            "receivedPath" = ${ReceivedPath}
            "parsedHeaders" = ${ParsedHeaders}
            "warnings" = ${Warnings}
            "errors" = ${Errors}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AnalyzeEmailHeadersResults<PSCustomObject>

.DESCRIPTION

Convert from JSON to AnalyzeEmailHeadersResults<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AnalyzeEmailHeadersResults<PSCustomObject>
#>
function ConvertFrom-JsonToAnalyzeEmailHeadersResults {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => AnalyzeEmailHeadersResults' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AnalyzeEmailHeadersResults
        $AllProperties = ("summary", "receivedPath", "parsedHeaders", "warnings", "errors")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'summary' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "summary"))) {
            throw "Error! JSON cannot be serialized due to the required property 'summary' missing."
        } else {
            $Summary = $JsonParameters.PSobject.Properties["summary"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "receivedPath"))) {
            throw "Error! JSON cannot be serialized due to the required property 'receivedPath' missing."
        } else {
            $ReceivedPath = $JsonParameters.PSobject.Properties["receivedPath"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "parsedHeaders"))) {
            throw "Error! JSON cannot be serialized due to the required property 'parsedHeaders' missing."
        } else {
            $ParsedHeaders = $JsonParameters.PSobject.Properties["parsedHeaders"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "warnings"))) {
            throw "Error! JSON cannot be serialized due to the required property 'warnings' missing."
        } else {
            $Warnings = $JsonParameters.PSobject.Properties["warnings"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "errors"))) {
            throw "Error! JSON cannot be serialized due to the required property 'errors' missing."
        } else {
            $Errors = $JsonParameters.PSobject.Properties["errors"].value
        }

        $PSO = [PSCustomObject]@{
            "summary" = ${Summary}
            "receivedPath" = ${ReceivedPath}
            "parsedHeaders" = ${ParsedHeaders}
            "warnings" = ${Warnings}
            "errors" = ${Errors}
        }

        return $PSO
    }

}

