#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

One-shot public domain monitor check options

.PARAMETER Domain
Domain to evaluate
.PARAMETER CaptchaToken
Optional captcha token when captcha protection is enabled
.OUTPUTS

CheckDomainMonitorOptions<PSCustomObject>
#>

function Initialize-CheckDomainMonitorOptions {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Domain},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CaptchaToken}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => CheckDomainMonitorOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Domain -eq $null) {
            throw "invalid value for 'Domain', 'Domain' cannot be null."
        }

        if ($Domain.length -lt 1) {
            throw "invalid value for 'Domain', the character length must be great than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "domain" = ${Domain}
            "captchaToken" = ${CaptchaToken}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CheckDomainMonitorOptions<PSCustomObject>

.DESCRIPTION

Convert from JSON to CheckDomainMonitorOptions<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CheckDomainMonitorOptions<PSCustomObject>
#>
function ConvertFrom-JsonToCheckDomainMonitorOptions {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => CheckDomainMonitorOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CheckDomainMonitorOptions
        $AllProperties = ("domain", "captchaToken")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'domain' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "domain"))) {
            throw "Error! JSON cannot be serialized due to the required property 'domain' missing."
        } else {
            $Domain = $JsonParameters.PSobject.Properties["domain"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "captchaToken"))) { #optional property not found
            $CaptchaToken = $null
        } else {
            $CaptchaToken = $JsonParameters.PSobject.Properties["captchaToken"].value
        }

        $PSO = [PSCustomObject]@{
            "domain" = ${Domain}
            "captchaToken" = ${CaptchaToken}
        }

        return $PSO
    }

}

