#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Create a new deliverability/load test

.PARAMETER Name
Optional name for the test
.PARAMETER Description
Optional description
.PARAMETER Scope
Entity scope to evaluate
.PARAMETER StartAt
UTC instant when the receive window starts. Defaults to now if omitted.
.PARAMETER MaxDurationSeconds
Optional timeout in seconds after startAt. If not all entities match before timeout the test transitions to FAILED.
.PARAMETER SuccessThresholdPercent
Optional acceptable success threshold percentage (0,100]. If set, a timed-out test can complete successfully when matchedEntities/totalEntities reaches this percentage.
.PARAMETER Selector
No description available.
.PARAMETER Expectations
One or more expectations to evaluate for each entity
.OUTPUTS

CreateDeliverabilityTestOptions<PSCustomObject>
#>

function Initialize-CreateDeliverabilityTestOptions {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("INBOX", "PHONE")]
        [String]
        ${Scope},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${StartAt},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${MaxDurationSeconds},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Double]]
        ${SuccessThresholdPercent},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Selector},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Expectations}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => CreateDeliverabilityTestOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Scope -eq $null) {
            throw "invalid value for 'Scope', 'Scope' cannot be null."
        }

        if ($MaxDurationSeconds -and $MaxDurationSeconds -lt 1) {
          throw "invalid value for 'MaxDurationSeconds', must be greater than or equal to 1."
        }

        if ($SuccessThresholdPercent -and $SuccessThresholdPercent -gt 100.0) {
          throw "invalid value for 'SuccessThresholdPercent', must be smaller than or equal to 100.0."
        }

        if ($SuccessThresholdPercent -and $SuccessThresholdPercent -le 0.0) {
          throw "invalid value for 'SuccessThresholdPercent', must be greater than 0.0."
        }

        if ($Selector -eq $null) {
            throw "invalid value for 'Selector', 'Selector' cannot be null."
        }

        if ($Expectations -eq $null) {
            throw "invalid value for 'Expectations', 'Expectations' cannot be null."
        }

        if ($Expectations.length -gt 20) {
            throw "invalid value for 'Expectations', number of items must be less than or equal to 20."
        }

        if ($Expectations.length -lt 1) {
            throw "invalid value for 'Expectations', number of items must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "description" = ${Description}
            "scope" = ${Scope}
            "startAt" = ${StartAt}
            "maxDurationSeconds" = ${MaxDurationSeconds}
            "successThresholdPercent" = ${SuccessThresholdPercent}
            "selector" = ${Selector}
            "expectations" = ${Expectations}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CreateDeliverabilityTestOptions<PSCustomObject>

.DESCRIPTION

Convert from JSON to CreateDeliverabilityTestOptions<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CreateDeliverabilityTestOptions<PSCustomObject>
#>
function ConvertFrom-JsonToCreateDeliverabilityTestOptions {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => CreateDeliverabilityTestOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CreateDeliverabilityTestOptions
        $AllProperties = ("name", "description", "scope", "startAt", "maxDurationSeconds", "successThresholdPercent", "selector", "expectations")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'scope' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "scope"))) {
            throw "Error! JSON cannot be serialized due to the required property 'scope' missing."
        } else {
            $Scope = $JsonParameters.PSobject.Properties["scope"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "selector"))) {
            throw "Error! JSON cannot be serialized due to the required property 'selector' missing."
        } else {
            $Selector = $JsonParameters.PSobject.Properties["selector"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "expectations"))) {
            throw "Error! JSON cannot be serialized due to the required property 'expectations' missing."
        } else {
            $Expectations = $JsonParameters.PSobject.Properties["expectations"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "startAt"))) { #optional property not found
            $StartAt = $null
        } else {
            $StartAt = $JsonParameters.PSobject.Properties["startAt"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "maxDurationSeconds"))) { #optional property not found
            $MaxDurationSeconds = $null
        } else {
            $MaxDurationSeconds = $JsonParameters.PSobject.Properties["maxDurationSeconds"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "successThresholdPercent"))) { #optional property not found
            $SuccessThresholdPercent = $null
        } else {
            $SuccessThresholdPercent = $JsonParameters.PSobject.Properties["successThresholdPercent"].value
        }

        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "description" = ${Description}
            "scope" = ${Scope}
            "startAt" = ${StartAt}
            "maxDurationSeconds" = ${MaxDurationSeconds}
            "successThresholdPercent" = ${SuccessThresholdPercent}
            "selector" = ${Selector}
            "expectations" = ${Expectations}
        }

        return $PSO
    }

}

