#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Enabled
No description available.
.PARAMETER SmtpHost
No description available.
.PARAMETER SmtpPort
No description available.
.PARAMETER SmtpSsl
No description available.
.PARAMETER SmtpUsername
No description available.
.PARAMETER SmtpPassword
No description available.
.PARAMETER SmtpMechanisms
No description available.
.PARAMETER StartTls
No description available.
.PARAMETER LocalHostName
No description available.
.PARAMETER ProxyHost
No description available.
.PARAMETER ProxyPort
No description available.
.PARAMETER ProxyEnabled
No description available.
.PARAMETER SslTrust
No description available.
.PARAMETER SslProtocols
No description available.
.OUTPUTS

CreateConnectorSmtpConnectionOptions<PSCustomObject>
#>

function Initialize-CreateConnectorSmtpConnectionOptions {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Enabled},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SmtpHost},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${SmtpPort},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${SmtpSsl},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SmtpUsername},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SmtpPassword},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${SmtpMechanisms},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${StartTls},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${LocalHostName},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProxyHost},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${ProxyPort},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ProxyEnabled},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SslTrust},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${SslProtocols}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => CreateConnectorSmtpConnectionOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($SmtpHost -eq $null) {
            throw "invalid value for 'SmtpHost', 'SmtpHost' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "enabled" = ${Enabled}
            "smtpHost" = ${SmtpHost}
            "smtpPort" = ${SmtpPort}
            "smtpSsl" = ${SmtpSsl}
            "smtpUsername" = ${SmtpUsername}
            "smtpPassword" = ${SmtpPassword}
            "smtpMechanisms" = ${SmtpMechanisms}
            "startTls" = ${StartTls}
            "localHostName" = ${LocalHostName}
            "proxyHost" = ${ProxyHost}
            "proxyPort" = ${ProxyPort}
            "proxyEnabled" = ${ProxyEnabled}
            "sslTrust" = ${SslTrust}
            "sslProtocols" = ${SslProtocols}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CreateConnectorSmtpConnectionOptions<PSCustomObject>

.DESCRIPTION

Convert from JSON to CreateConnectorSmtpConnectionOptions<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CreateConnectorSmtpConnectionOptions<PSCustomObject>
#>
function ConvertFrom-JsonToCreateConnectorSmtpConnectionOptions {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => CreateConnectorSmtpConnectionOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CreateConnectorSmtpConnectionOptions
        $AllProperties = ("enabled", "smtpHost", "smtpPort", "smtpSsl", "smtpUsername", "smtpPassword", "smtpMechanisms", "startTls", "localHostName", "proxyHost", "proxyPort", "proxyEnabled", "sslTrust", "sslProtocols")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'smtpHost' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "smtpHost"))) {
            throw "Error! JSON cannot be serialized due to the required property 'smtpHost' missing."
        } else {
            $SmtpHost = $JsonParameters.PSobject.Properties["smtpHost"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enabled"))) { #optional property not found
            $Enabled = $null
        } else {
            $Enabled = $JsonParameters.PSobject.Properties["enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "smtpPort"))) { #optional property not found
            $SmtpPort = $null
        } else {
            $SmtpPort = $JsonParameters.PSobject.Properties["smtpPort"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "smtpSsl"))) { #optional property not found
            $SmtpSsl = $null
        } else {
            $SmtpSsl = $JsonParameters.PSobject.Properties["smtpSsl"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "smtpUsername"))) { #optional property not found
            $SmtpUsername = $null
        } else {
            $SmtpUsername = $JsonParameters.PSobject.Properties["smtpUsername"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "smtpPassword"))) { #optional property not found
            $SmtpPassword = $null
        } else {
            $SmtpPassword = $JsonParameters.PSobject.Properties["smtpPassword"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "smtpMechanisms"))) { #optional property not found
            $SmtpMechanisms = $null
        } else {
            $SmtpMechanisms = $JsonParameters.PSobject.Properties["smtpMechanisms"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "startTls"))) { #optional property not found
            $StartTls = $null
        } else {
            $StartTls = $JsonParameters.PSobject.Properties["startTls"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "localHostName"))) { #optional property not found
            $LocalHostName = $null
        } else {
            $LocalHostName = $JsonParameters.PSobject.Properties["localHostName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "proxyHost"))) { #optional property not found
            $ProxyHost = $null
        } else {
            $ProxyHost = $JsonParameters.PSobject.Properties["proxyHost"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "proxyPort"))) { #optional property not found
            $ProxyPort = $null
        } else {
            $ProxyPort = $JsonParameters.PSobject.Properties["proxyPort"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "proxyEnabled"))) { #optional property not found
            $ProxyEnabled = $null
        } else {
            $ProxyEnabled = $JsonParameters.PSobject.Properties["proxyEnabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sslTrust"))) { #optional property not found
            $SslTrust = $null
        } else {
            $SslTrust = $JsonParameters.PSobject.Properties["sslTrust"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sslProtocols"))) { #optional property not found
            $SslProtocols = $null
        } else {
            $SslProtocols = $JsonParameters.PSobject.Properties["sslProtocols"].value
        }

        $PSO = [PSCustomObject]@{
            "enabled" = ${Enabled}
            "smtpHost" = ${SmtpHost}
            "smtpPort" = ${SmtpPort}
            "smtpSsl" = ${SmtpSsl}
            "smtpUsername" = ${SmtpUsername}
            "smtpPassword" = ${SmtpPassword}
            "smtpMechanisms" = ${SmtpMechanisms}
            "startTls" = ${StartTls}
            "localHostName" = ${LocalHostName}
            "proxyHost" = ${ProxyHost}
            "proxyPort" = ${ProxyPort}
            "proxyEnabled" = ${ProxyEnabled}
            "sslTrust" = ${SslTrust}
            "sslProtocols" = ${SslProtocols}
        }

        return $PSO
    }

}

