#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER RunId
No description available.
.PARAMETER EmailId
No description available.
.PARAMETER Status
No description available.
.PARAMETER PrimaryScreenshotId
No description available.
.PARAMETER RequestedProviders
No description available.
.PARAMETER ImportedProviders
No description available.
.PARAMETER Warnings
No description available.
.PARAMETER ProviderMessageIds
No description available.
.PARAMETER TargetCount
No description available.
.PARAMETER ScreenshotCount
No description available.
.PARAMETER CreatedAt
No description available.
.PARAMETER UpdatedAt
No description available.
.OUTPUTS

DevicePreviewRunDto<PSCustomObject>
#>

function Initialize-DevicePreviewRunDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${RunId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EmailId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("CREATED", "AWAITING_ARRIVAL", "CAPTURING", "PARTIAL_COMPLETE", "COMPLETE", "FAILED")]
        [String]
        ${Status},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PrimaryScreenshotId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("GMAIL", "OUTLOOK", "YAHOO")]
        [String[]]
        ${RequestedProviders},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("GMAIL", "OUTLOOK", "YAHOO")]
        [String[]]
        ${ImportedProviders},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Warnings},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Collections.Hashtable]
        ${ProviderMessageIds},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [Int64]
        ${TargetCount},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [Int64]
        ${ScreenshotCount},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [System.DateTime]
        ${CreatedAt},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [System.DateTime]
        ${UpdatedAt}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => DevicePreviewRunDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($RunId -eq $null) {
            throw "invalid value for 'RunId', 'RunId' cannot be null."
        }

        if ($EmailId -eq $null) {
            throw "invalid value for 'EmailId', 'EmailId' cannot be null."
        }

        if ($Status -eq $null) {
            throw "invalid value for 'Status', 'Status' cannot be null."
        }

        if ($TargetCount -eq $null) {
            throw "invalid value for 'TargetCount', 'TargetCount' cannot be null."
        }

        if ($ScreenshotCount -eq $null) {
            throw "invalid value for 'ScreenshotCount', 'ScreenshotCount' cannot be null."
        }

        if ($CreatedAt -eq $null) {
            throw "invalid value for 'CreatedAt', 'CreatedAt' cannot be null."
        }

        if ($UpdatedAt -eq $null) {
            throw "invalid value for 'UpdatedAt', 'UpdatedAt' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "runId" = ${RunId}
            "emailId" = ${EmailId}
            "status" = ${Status}
            "primaryScreenshotId" = ${PrimaryScreenshotId}
            "requestedProviders" = ${RequestedProviders}
            "importedProviders" = ${ImportedProviders}
            "warnings" = ${Warnings}
            "providerMessageIds" = ${ProviderMessageIds}
            "targetCount" = ${TargetCount}
            "screenshotCount" = ${ScreenshotCount}
            "createdAt" = ${CreatedAt}
            "updatedAt" = ${UpdatedAt}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DevicePreviewRunDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to DevicePreviewRunDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DevicePreviewRunDto<PSCustomObject>
#>
function ConvertFrom-JsonToDevicePreviewRunDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => DevicePreviewRunDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DevicePreviewRunDto
        $AllProperties = ("runId", "emailId", "status", "primaryScreenshotId", "requestedProviders", "importedProviders", "warnings", "providerMessageIds", "targetCount", "screenshotCount", "createdAt", "updatedAt")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'runId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "runId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'runId' missing."
        } else {
            $RunId = $JsonParameters.PSobject.Properties["runId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "emailId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'emailId' missing."
        } else {
            $EmailId = $JsonParameters.PSobject.Properties["emailId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "status"))) {
            throw "Error! JSON cannot be serialized due to the required property 'status' missing."
        } else {
            $Status = $JsonParameters.PSobject.Properties["status"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "targetCount"))) {
            throw "Error! JSON cannot be serialized due to the required property 'targetCount' missing."
        } else {
            $TargetCount = $JsonParameters.PSobject.Properties["targetCount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "screenshotCount"))) {
            throw "Error! JSON cannot be serialized due to the required property 'screenshotCount' missing."
        } else {
            $ScreenshotCount = $JsonParameters.PSobject.Properties["screenshotCount"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "createdAt"))) {
            throw "Error! JSON cannot be serialized due to the required property 'createdAt' missing."
        } else {
            $CreatedAt = $JsonParameters.PSobject.Properties["createdAt"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "updatedAt"))) {
            throw "Error! JSON cannot be serialized due to the required property 'updatedAt' missing."
        } else {
            $UpdatedAt = $JsonParameters.PSobject.Properties["updatedAt"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "primaryScreenshotId"))) { #optional property not found
            $PrimaryScreenshotId = $null
        } else {
            $PrimaryScreenshotId = $JsonParameters.PSobject.Properties["primaryScreenshotId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "requestedProviders"))) { #optional property not found
            $RequestedProviders = $null
        } else {
            $RequestedProviders = $JsonParameters.PSobject.Properties["requestedProviders"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "importedProviders"))) { #optional property not found
            $ImportedProviders = $null
        } else {
            $ImportedProviders = $JsonParameters.PSobject.Properties["importedProviders"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "warnings"))) { #optional property not found
            $Warnings = $null
        } else {
            $Warnings = $JsonParameters.PSobject.Properties["warnings"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "providerMessageIds"))) { #optional property not found
            $ProviderMessageIds = $null
        } else {
            $ProviderMessageIds = $JsonParameters.PSobject.Properties["providerMessageIds"].value
        }

        $PSO = [PSCustomObject]@{
            "runId" = ${RunId}
            "emailId" = ${EmailId}
            "status" = ${Status}
            "primaryScreenshotId" = ${PrimaryScreenshotId}
            "requestedProviders" = ${RequestedProviders}
            "importedProviders" = ${ImportedProviders}
            "warnings" = ${Warnings}
            "providerMessageIds" = ${ProviderMessageIds}
            "targetCount" = ${TargetCount}
            "screenshotCount" = ${ScreenshotCount}
            "createdAt" = ${CreatedAt}
            "updatedAt" = ${UpdatedAt}
        }

        return $PSO
    }

}

