#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Propagation results from a single DNS resolver

.PARAMETER Resolver
No description available.
.PARAMETER Records
No description available.
.PARAMETER Responded
No description available.
.PARAMETER MatchedExpectedValue
No description available.
.OUTPUTS

DnsPropagationResolverResult<PSCustomObject>
#>

function Initialize-DnsPropagationResolverResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Resolver},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Records},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Responded},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${MatchedExpectedValue}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => DnsPropagationResolverResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Resolver -eq $null) {
            throw "invalid value for 'Resolver', 'Resolver' cannot be null."
        }

        if ($Records -eq $null) {
            throw "invalid value for 'Records', 'Records' cannot be null."
        }

        if ($Responded -eq $null) {
            throw "invalid value for 'Responded', 'Responded' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "resolver" = ${Resolver}
            "records" = ${Records}
            "responded" = ${Responded}
            "matchedExpectedValue" = ${MatchedExpectedValue}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DnsPropagationResolverResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to DnsPropagationResolverResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DnsPropagationResolverResult<PSCustomObject>
#>
function ConvertFrom-JsonToDnsPropagationResolverResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => DnsPropagationResolverResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DnsPropagationResolverResult
        $AllProperties = ("resolver", "records", "responded", "matchedExpectedValue")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'resolver' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "resolver"))) {
            throw "Error! JSON cannot be serialized due to the required property 'resolver' missing."
        } else {
            $Resolver = $JsonParameters.PSobject.Properties["resolver"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "records"))) {
            throw "Error! JSON cannot be serialized due to the required property 'records' missing."
        } else {
            $Records = $JsonParameters.PSobject.Properties["records"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "responded"))) {
            throw "Error! JSON cannot be serialized due to the required property 'responded' missing."
        } else {
            $Responded = $JsonParameters.PSobject.Properties["responded"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "matchedExpectedValue"))) { #optional property not found
            $MatchedExpectedValue = $null
        } else {
            $MatchedExpectedValue = $JsonParameters.PSobject.Properties["matchedExpectedValue"].value
        }

        $PSO = [PSCustomObject]@{
            "resolver" = ${Resolver}
            "records" = ${Records}
            "responded" = ${Responded}
            "matchedExpectedValue" = ${MatchedExpectedValue}
        }

        return $PSO
    }

}

