#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Label
No description available.
.PARAMETER Domains
No description available.
.OUTPUTS

DomainGroup<PSCustomObject>
#>

function Initialize-DomainGroup {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("DEFAULT", "DOMAIN_POOL", "CUSTOM")]
        [String]
        ${Label},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Domains}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => DomainGroup' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Label -eq $null) {
            throw "invalid value for 'Label', 'Label' cannot be null."
        }

        if ($Domains -eq $null) {
            throw "invalid value for 'Domains', 'Domains' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "label" = ${Label}
            "domains" = ${Domains}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DomainGroup<PSCustomObject>

.DESCRIPTION

Convert from JSON to DomainGroup<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DomainGroup<PSCustomObject>
#>
function ConvertFrom-JsonToDomainGroup {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => DomainGroup' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DomainGroup
        $AllProperties = ("label", "domains")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'label' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "label"))) {
            throw "Error! JSON cannot be serialized due to the required property 'label' missing."
        } else {
            $Label = $JsonParameters.PSobject.Properties["label"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "domains"))) {
            throw "Error! JSON cannot be serialized due to the required property 'domains' missing."
        } else {
            $Domains = $JsonParameters.PSobject.Properties["domains"].value
        }

        $PSO = [PSCustomObject]@{
            "label" = ${Label}
            "domains" = ${Domains}
        }

        return $PSO
    }

}

