#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Matches for the given pattern

.PARAMETER Pattern
No description available.
.PARAMETER VarMatches
No description available.
.OUTPUTS

EmailContentMatchResult<PSCustomObject>
#>

function Initialize-EmailContentMatchResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Pattern},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${VarMatches}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => EmailContentMatchResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Pattern -eq $null) {
            throw "invalid value for 'Pattern', 'Pattern' cannot be null."
        }

        if ($VarMatches -eq $null) {
            throw "invalid value for 'VarMatches', 'VarMatches' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "pattern" = ${Pattern}
            "matches" = ${VarMatches}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to EmailContentMatchResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to EmailContentMatchResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

EmailContentMatchResult<PSCustomObject>
#>
function ConvertFrom-JsonToEmailContentMatchResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => EmailContentMatchResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in EmailContentMatchResult
        $AllProperties = ("pattern", "matches")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'pattern' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "pattern"))) {
            throw "Error! JSON cannot be serialized due to the required property 'pattern' missing."
        } else {
            $Pattern = $JsonParameters.PSobject.Properties["pattern"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "matches"))) {
            throw "Error! JSON cannot be serialized due to the required property 'matches' missing."
        } else {
            $VarMatches = $JsonParameters.PSobject.Properties["matches"].value
        }

        $PSO = [PSCustomObject]@{
            "pattern" = ${Pattern}
            "matches" = ${VarMatches}
        }

        return $PSO
    }

}

