#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER VarFrom
No description available.
.PARAMETER By
No description available.
.PARAMETER WithValue
No description available.
.PARAMETER Timestamp
No description available.
.PARAMETER DelayMs
No description available.
.OUTPUTS

EmailHeaderReceivedHop<PSCustomObject>
#>

function Initialize-EmailHeaderReceivedHop {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VarFrom},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${By},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${WithValue},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Timestamp},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${DelayMs}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => EmailHeaderReceivedHop' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "from" = ${VarFrom}
            "by" = ${By}
            "withValue" = ${WithValue}
            "timestamp" = ${Timestamp}
            "delayMs" = ${DelayMs}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to EmailHeaderReceivedHop<PSCustomObject>

.DESCRIPTION

Convert from JSON to EmailHeaderReceivedHop<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

EmailHeaderReceivedHop<PSCustomObject>
#>
function ConvertFrom-JsonToEmailHeaderReceivedHop {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => EmailHeaderReceivedHop' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in EmailHeaderReceivedHop
        $AllProperties = ("from", "by", "withValue", "timestamp", "delayMs")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "from"))) { #optional property not found
            $VarFrom = $null
        } else {
            $VarFrom = $JsonParameters.PSobject.Properties["from"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "by"))) { #optional property not found
            $By = $null
        } else {
            $By = $JsonParameters.PSobject.Properties["by"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "withValue"))) { #optional property not found
            $WithValue = $null
        } else {
            $WithValue = $JsonParameters.PSobject.Properties["withValue"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "delayMs"))) { #optional property not found
            $DelayMs = $null
        } else {
            $DelayMs = $JsonParameters.PSobject.Properties["delayMs"].value
        }

        $PSO = [PSCustomObject]@{
            "from" = ${VarFrom}
            "by" = ${By}
            "withValue" = ${WithValue}
            "timestamp" = ${Timestamp}
            "delayMs" = ${DelayMs}
        }

        return $PSO
    }

}

