#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Issuer
No description available.
.PARAMETER NameId
No description available.
.PARAMETER NameIdFormat
No description available.
.OUTPUTS

GetOrCreateSamlUserOptions<PSCustomObject>
#>

function Initialize-GetOrCreateSamlUserOptions {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Issuer},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${NameId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${NameIdFormat}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => GetOrCreateSamlUserOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Issuer -eq $null) {
            throw "invalid value for 'Issuer', 'Issuer' cannot be null."
        }

        if ($NameId -eq $null) {
            throw "invalid value for 'NameId', 'NameId' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "issuer" = ${Issuer}
            "nameId" = ${NameId}
            "nameIdFormat" = ${NameIdFormat}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to GetOrCreateSamlUserOptions<PSCustomObject>

.DESCRIPTION

Convert from JSON to GetOrCreateSamlUserOptions<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

GetOrCreateSamlUserOptions<PSCustomObject>
#>
function ConvertFrom-JsonToGetOrCreateSamlUserOptions {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => GetOrCreateSamlUserOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in GetOrCreateSamlUserOptions
        $AllProperties = ("issuer", "nameId", "nameIdFormat")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'issuer' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "issuer"))) {
            throw "Error! JSON cannot be serialized due to the required property 'issuer' missing."
        } else {
            $Issuer = $JsonParameters.PSobject.Properties["issuer"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "nameId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'nameId' missing."
        } else {
            $NameId = $JsonParameters.PSobject.Properties["nameId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "nameIdFormat"))) { #optional property not found
            $NameIdFormat = $null
        } else {
            $NameIdFormat = $JsonParameters.PSobject.Properties["nameIdFormat"].value
        }

        $PSO = [PSCustomObject]@{
            "issuer" = ${Issuer}
            "nameId" = ${NameId}
            "nameIdFormat" = ${NameIdFormat}
        }

        return $PSO
    }

}

