#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER SmtpServerHost
No description available.
.PARAMETER SmtpServerPort
No description available.
.PARAMETER SmtpUsername
No description available.
.PARAMETER SmtpPassword
No description available.
.PARAMETER ImapServerHost
No description available.
.PARAMETER ImapServerPort
No description available.
.PARAMETER ImapUsername
No description available.
.PARAMETER ImapPassword
No description available.
.OUTPUTS

ImapSmtpAccessDetails<PSCustomObject>
#>

function Initialize-ImapSmtpAccessDetails {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SmtpServerHost},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${SmtpServerPort},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SmtpUsername},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SmtpPassword},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ImapServerHost},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${ImapServerPort},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ImapUsername},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ImapPassword}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => ImapSmtpAccessDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($SmtpServerHost -eq $null) {
            throw "invalid value for 'SmtpServerHost', 'SmtpServerHost' cannot be null."
        }

        if ($SmtpServerPort -eq $null) {
            throw "invalid value for 'SmtpServerPort', 'SmtpServerPort' cannot be null."
        }

        if ($SmtpUsername -eq $null) {
            throw "invalid value for 'SmtpUsername', 'SmtpUsername' cannot be null."
        }

        if ($SmtpPassword -eq $null) {
            throw "invalid value for 'SmtpPassword', 'SmtpPassword' cannot be null."
        }

        if ($ImapServerHost -eq $null) {
            throw "invalid value for 'ImapServerHost', 'ImapServerHost' cannot be null."
        }

        if ($ImapServerPort -eq $null) {
            throw "invalid value for 'ImapServerPort', 'ImapServerPort' cannot be null."
        }

        if ($ImapUsername -eq $null) {
            throw "invalid value for 'ImapUsername', 'ImapUsername' cannot be null."
        }

        if ($ImapPassword -eq $null) {
            throw "invalid value for 'ImapPassword', 'ImapPassword' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "smtpServerHost" = ${SmtpServerHost}
            "smtpServerPort" = ${SmtpServerPort}
            "smtpUsername" = ${SmtpUsername}
            "smtpPassword" = ${SmtpPassword}
            "imapServerHost" = ${ImapServerHost}
            "imapServerPort" = ${ImapServerPort}
            "imapUsername" = ${ImapUsername}
            "imapPassword" = ${ImapPassword}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ImapSmtpAccessDetails<PSCustomObject>

.DESCRIPTION

Convert from JSON to ImapSmtpAccessDetails<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ImapSmtpAccessDetails<PSCustomObject>
#>
function ConvertFrom-JsonToImapSmtpAccessDetails {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => ImapSmtpAccessDetails' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ImapSmtpAccessDetails
        $AllProperties = ("smtpServerHost", "smtpServerPort", "smtpUsername", "smtpPassword", "imapServerHost", "imapServerPort", "imapUsername", "imapPassword")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'smtpServerHost' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "smtpServerHost"))) {
            throw "Error! JSON cannot be serialized due to the required property 'smtpServerHost' missing."
        } else {
            $SmtpServerHost = $JsonParameters.PSobject.Properties["smtpServerHost"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "smtpServerPort"))) {
            throw "Error! JSON cannot be serialized due to the required property 'smtpServerPort' missing."
        } else {
            $SmtpServerPort = $JsonParameters.PSobject.Properties["smtpServerPort"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "smtpUsername"))) {
            throw "Error! JSON cannot be serialized due to the required property 'smtpUsername' missing."
        } else {
            $SmtpUsername = $JsonParameters.PSobject.Properties["smtpUsername"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "smtpPassword"))) {
            throw "Error! JSON cannot be serialized due to the required property 'smtpPassword' missing."
        } else {
            $SmtpPassword = $JsonParameters.PSobject.Properties["smtpPassword"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "imapServerHost"))) {
            throw "Error! JSON cannot be serialized due to the required property 'imapServerHost' missing."
        } else {
            $ImapServerHost = $JsonParameters.PSobject.Properties["imapServerHost"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "imapServerPort"))) {
            throw "Error! JSON cannot be serialized due to the required property 'imapServerPort' missing."
        } else {
            $ImapServerPort = $JsonParameters.PSobject.Properties["imapServerPort"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "imapUsername"))) {
            throw "Error! JSON cannot be serialized due to the required property 'imapUsername' missing."
        } else {
            $ImapUsername = $JsonParameters.PSobject.Properties["imapUsername"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "imapPassword"))) {
            throw "Error! JSON cannot be serialized due to the required property 'imapPassword' missing."
        } else {
            $ImapPassword = $JsonParameters.PSobject.Properties["imapPassword"].value
        }

        $PSO = [PSCustomObject]@{
            "smtpServerHost" = ${SmtpServerHost}
            "smtpServerPort" = ${SmtpServerPort}
            "smtpUsername" = ${SmtpUsername}
            "smtpPassword" = ${SmtpPassword}
            "imapServerHost" = ${ImapServerHost}
            "imapServerPort" = ${ImapServerPort}
            "imapUsername" = ${ImapUsername}
            "imapPassword" = ${ImapPassword}
        }

        return $PSO
    }

}

