#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Single inbox automation match rule.

.PARAMETER Field
Supported fields for inbox forwarder and replier automation matching.
.PARAMETER Should
Comparison mode for inbox automation matching.
.PARAMETER Value
Pattern or value to compare against the selected field.
.OUTPUTS

InboxAutomationMatchOption<PSCustomObject>
#>

function Initialize-InboxAutomationMatchOption {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("RECIPIENTS", "SENDER", "SUBJECT", "ATTACHMENTS", "ATTACHMENT_FILENAME", "ATTACHMENT_TEXT")]
        [String]
        ${Field},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("WILDCARD", "MATCH", "CONTAIN", "EQUAL")]
        [String]
        ${Should},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Value}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => InboxAutomationMatchOption' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Field -eq $null) {
            throw "invalid value for 'Field', 'Field' cannot be null."
        }

        if ($Should -eq $null) {
            throw "invalid value for 'Should', 'Should' cannot be null."
        }

        if ($Value -eq $null) {
            throw "invalid value for 'Value', 'Value' cannot be null."
        }

        if ($Value.length -lt 1) {
            throw "invalid value for 'Value', the character length must be great than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "field" = ${Field}
            "should" = ${Should}
            "value" = ${Value}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to InboxAutomationMatchOption<PSCustomObject>

.DESCRIPTION

Convert from JSON to InboxAutomationMatchOption<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

InboxAutomationMatchOption<PSCustomObject>
#>
function ConvertFrom-JsonToInboxAutomationMatchOption {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => InboxAutomationMatchOption' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in InboxAutomationMatchOption
        $AllProperties = ("field", "should", "value")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'field' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "field"))) {
            throw "Error! JSON cannot be serialized due to the required property 'field' missing."
        } else {
            $Field = $JsonParameters.PSobject.Properties["field"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "should"))) {
            throw "Error! JSON cannot be serialized due to the required property 'should' missing."
        } else {
            $Should = $JsonParameters.PSobject.Properties["should"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "value"))) {
            throw "Error! JSON cannot be serialized due to the required property 'value' missing."
        } else {
            $Value = $JsonParameters.PSobject.Properties["value"].value
        }

        $PSO = [PSCustomObject]@{
            "field" = ${Field}
            "should" = ${Should}
            "value" = ${Value}
        }

        return $PSO
    }

}

