#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER VerificationCodeSent
No description available.
.PARAMETER UserHasConsented
No description available.
.PARAMETER CanSend
No description available.
.OUTPUTS

OptInSendingConsentDto<PSCustomObject>
#>

function Initialize-OptInSendingConsentDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${VerificationCodeSent},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${UserHasConsented},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${CanSend}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => OptInSendingConsentDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($VerificationCodeSent -eq $null) {
            throw "invalid value for 'VerificationCodeSent', 'VerificationCodeSent' cannot be null."
        }

        if ($UserHasConsented -eq $null) {
            throw "invalid value for 'UserHasConsented', 'UserHasConsented' cannot be null."
        }

        if ($CanSend -eq $null) {
            throw "invalid value for 'CanSend', 'CanSend' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "verificationCodeSent" = ${VerificationCodeSent}
            "userHasConsented" = ${UserHasConsented}
            "canSend" = ${CanSend}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to OptInSendingConsentDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to OptInSendingConsentDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

OptInSendingConsentDto<PSCustomObject>
#>
function ConvertFrom-JsonToOptInSendingConsentDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => OptInSendingConsentDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in OptInSendingConsentDto
        $AllProperties = ("verificationCodeSent", "userHasConsented", "canSend")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'verificationCodeSent' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "verificationCodeSent"))) {
            throw "Error! JSON cannot be serialized due to the required property 'verificationCodeSent' missing."
        } else {
            $VerificationCodeSent = $JsonParameters.PSobject.Properties["verificationCodeSent"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "userHasConsented"))) {
            throw "Error! JSON cannot be serialized due to the required property 'userHasConsented' missing."
        } else {
            $UserHasConsented = $JsonParameters.PSobject.Properties["userHasConsented"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "canSend"))) {
            throw "Error! JSON cannot be serialized due to the required property 'canSend' missing."
        } else {
            $CanSend = $JsonParameters.PSobject.Properties["canSend"].value
        }

        $PSO = [PSCustomObject]@{
            "verificationCodeSent" = ${VerificationCodeSent}
            "userHasConsented" = ${UserHasConsented}
            "canSend" = ${CanSend}
        }

        return $PSO
    }

}

