#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Headers
No description available.
.PARAMETER Rows
No description available.
.PARAMETER Pagination
No description available.
.OUTPUTS

PageTableData<PSCustomObject>
#>

function Initialize-PageTableData {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Headers},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String[][]]
        ${Rows},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Pagination}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => PageTableData' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Headers -eq $null) {
            throw "invalid value for 'Headers', 'Headers' cannot be null."
        }

        if ($Rows -eq $null) {
            throw "invalid value for 'Rows', 'Rows' cannot be null."
        }

        if ($Pagination -eq $null) {
            throw "invalid value for 'Pagination', 'Pagination' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "headers" = ${Headers}
            "rows" = ${Rows}
            "pagination" = ${Pagination}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PageTableData<PSCustomObject>

.DESCRIPTION

Convert from JSON to PageTableData<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PageTableData<PSCustomObject>
#>
function ConvertFrom-JsonToPageTableData {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => PageTableData' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PageTableData
        $AllProperties = ("headers", "rows", "pagination")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'headers' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "headers"))) {
            throw "Error! JSON cannot be serialized due to the required property 'headers' missing."
        } else {
            $Headers = $JsonParameters.PSobject.Properties["headers"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "rows"))) {
            throw "Error! JSON cannot be serialized due to the required property 'rows' missing."
        } else {
            $Rows = $JsonParameters.PSobject.Properties["rows"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "pagination"))) {
            throw "Error! JSON cannot be serialized due to the required property 'pagination' missing."
        } else {
            $Pagination = $JsonParameters.PSobject.Properties["pagination"].value
        }

        $PSO = [PSCustomObject]@{
            "headers" = ${Headers}
            "rows" = ${Rows}
            "pagination" = ${Pagination}
        }

        return $PSO
    }

}

