#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
No description available.
.PARAMETER Name
No description available.
.PARAMETER Description
No description available.
.PARAMETER UserId
No description available.
.PARAMETER ComplianceAddress
No description available.
.PARAMETER EmergencyAddress
No description available.
.PARAMETER PhoneNumber
No description available.
.PARAMETER PhoneCountry
No description available.
.PARAMETER PhonePlan
No description available.
.PARAMETER CreatedAt
No description available.
.PARAMETER UpdatedAt
No description available.
.PARAMETER Favourite
No description available.
.OUTPUTS

PhoneNumberDto<PSCustomObject>
#>

function Initialize-PhoneNumberDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${UserId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ComplianceAddress},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${EmergencyAddress},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PhoneNumber},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("US", "GB", "AU")]
        [String]
        ${PhoneCountry},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PhonePlan},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.DateTime]
        ${CreatedAt},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [System.DateTime]
        ${UpdatedAt},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Favourite}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => PhoneNumberDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Id -eq $null) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }

        if ($UserId -eq $null) {
            throw "invalid value for 'UserId', 'UserId' cannot be null."
        }

        if ($PhoneNumber -eq $null) {
            throw "invalid value for 'PhoneNumber', 'PhoneNumber' cannot be null."
        }

        if ($PhoneCountry -eq $null) {
            throw "invalid value for 'PhoneCountry', 'PhoneCountry' cannot be null."
        }

        if ($PhonePlan -eq $null) {
            throw "invalid value for 'PhonePlan', 'PhonePlan' cannot be null."
        }

        if ($CreatedAt -eq $null) {
            throw "invalid value for 'CreatedAt', 'CreatedAt' cannot be null."
        }

        if ($UpdatedAt -eq $null) {
            throw "invalid value for 'UpdatedAt', 'UpdatedAt' cannot be null."
        }

        if ($Favourite -eq $null) {
            throw "invalid value for 'Favourite', 'Favourite' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "name" = ${Name}
            "description" = ${Description}
            "userId" = ${UserId}
            "complianceAddress" = ${ComplianceAddress}
            "emergencyAddress" = ${EmergencyAddress}
            "phoneNumber" = ${PhoneNumber}
            "phoneCountry" = ${PhoneCountry}
            "phonePlan" = ${PhonePlan}
            "createdAt" = ${CreatedAt}
            "updatedAt" = ${UpdatedAt}
            "favourite" = ${Favourite}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PhoneNumberDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to PhoneNumberDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PhoneNumberDto<PSCustomObject>
#>
function ConvertFrom-JsonToPhoneNumberDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => PhoneNumberDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PhoneNumberDto
        $AllProperties = ("id", "name", "description", "userId", "complianceAddress", "emergencyAddress", "phoneNumber", "phoneCountry", "phonePlan", "createdAt", "updatedAt", "favourite")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'id' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "userId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'userId' missing."
        } else {
            $UserId = $JsonParameters.PSobject.Properties["userId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "phoneNumber"))) {
            throw "Error! JSON cannot be serialized due to the required property 'phoneNumber' missing."
        } else {
            $PhoneNumber = $JsonParameters.PSobject.Properties["phoneNumber"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "phoneCountry"))) {
            throw "Error! JSON cannot be serialized due to the required property 'phoneCountry' missing."
        } else {
            $PhoneCountry = $JsonParameters.PSobject.Properties["phoneCountry"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "phonePlan"))) {
            throw "Error! JSON cannot be serialized due to the required property 'phonePlan' missing."
        } else {
            $PhonePlan = $JsonParameters.PSobject.Properties["phonePlan"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "createdAt"))) {
            throw "Error! JSON cannot be serialized due to the required property 'createdAt' missing."
        } else {
            $CreatedAt = $JsonParameters.PSobject.Properties["createdAt"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "updatedAt"))) {
            throw "Error! JSON cannot be serialized due to the required property 'updatedAt' missing."
        } else {
            $UpdatedAt = $JsonParameters.PSobject.Properties["updatedAt"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "favourite"))) {
            throw "Error! JSON cannot be serialized due to the required property 'favourite' missing."
        } else {
            $Favourite = $JsonParameters.PSobject.Properties["favourite"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "complianceAddress"))) { #optional property not found
            $ComplianceAddress = $null
        } else {
            $ComplianceAddress = $JsonParameters.PSobject.Properties["complianceAddress"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "emergencyAddress"))) { #optional property not found
            $EmergencyAddress = $null
        } else {
            $EmergencyAddress = $JsonParameters.PSobject.Properties["emergencyAddress"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "name" = ${Name}
            "description" = ${Description}
            "userId" = ${UserId}
            "complianceAddress" = ${ComplianceAddress}
            "emergencyAddress" = ${EmergencyAddress}
            "phoneNumber" = ${PhoneNumber}
            "phoneCountry" = ${PhoneCountry}
            "phonePlan" = ${PhonePlan}
            "createdAt" = ${CreatedAt}
            "updatedAt" = ${UpdatedAt}
            "favourite" = ${Favourite}
        }

        return $PSO
    }

}

