#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER SubscriptionSchedule
No description available.
.PARAMETER PhoneCountry
No description available.
.OUTPUTS

PlanSummaryDto<PSCustomObject>
#>

function Initialize-PlanSummaryDto {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("MONTHLY", "YEARLY")]
        [String]
        ${SubscriptionSchedule},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("US", "GB", "AU", "CA", "EE", "HK", "PL", "PT", "NL", "IL", "FI", "SE")]
        [String]
        ${PhoneCountry}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => PlanSummaryDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($PhoneCountry -eq $null) {
            throw "invalid value for 'PhoneCountry', 'PhoneCountry' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "subscriptionSchedule" = ${SubscriptionSchedule}
            "phoneCountry" = ${PhoneCountry}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PlanSummaryDto<PSCustomObject>

.DESCRIPTION

Convert from JSON to PlanSummaryDto<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PlanSummaryDto<PSCustomObject>
#>
function ConvertFrom-JsonToPlanSummaryDto {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => PlanSummaryDto' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PlanSummaryDto
        $AllProperties = ("subscriptionSchedule", "phoneCountry")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'phoneCountry' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "phoneCountry"))) {
            throw "Error! JSON cannot be serialized due to the required property 'phoneCountry' missing."
        } else {
            $PhoneCountry = $JsonParameters.PSobject.Properties["phoneCountry"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "subscriptionSchedule"))) { #optional property not found
            $SubscriptionSchedule = $null
        } else {
            $SubscriptionSchedule = $JsonParameters.PSobject.Properties["subscriptionSchedule"].value
        }

        $PSO = [PSCustomObject]@{
            "subscriptionSchedule" = ${SubscriptionSchedule}
            "phoneCountry" = ${PhoneCountry}
        }

        return $PSO
    }

}

