#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER VarHost
No description available.
.PARAMETER Port
No description available.
.PARAMETER Tls
No description available.
.PARAMETER AltPorts
No description available.
.OUTPUTS

ServerEndpoints<PSCustomObject>
#>

function Initialize-ServerEndpoints {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VarHost},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${Port},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Tls},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [Int32[]]
        ${AltPorts}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => ServerEndpoints' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($VarHost -eq $null) {
            throw "invalid value for 'VarHost', 'VarHost' cannot be null."
        }

        if ($Port -eq $null) {
            throw "invalid value for 'Port', 'Port' cannot be null."
        }

        if ($Tls -eq $null) {
            throw "invalid value for 'Tls', 'Tls' cannot be null."
        }

        if ($AltPorts -eq $null) {
            throw "invalid value for 'AltPorts', 'AltPorts' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "host" = ${VarHost}
            "port" = ${Port}
            "tls" = ${Tls}
            "altPorts" = ${AltPorts}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ServerEndpoints<PSCustomObject>

.DESCRIPTION

Convert from JSON to ServerEndpoints<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ServerEndpoints<PSCustomObject>
#>
function ConvertFrom-JsonToServerEndpoints {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => ServerEndpoints' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ServerEndpoints
        $AllProperties = ("host", "port", "tls", "altPorts")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'host' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "host"))) {
            throw "Error! JSON cannot be serialized due to the required property 'host' missing."
        } else {
            $VarHost = $JsonParameters.PSobject.Properties["host"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "port"))) {
            throw "Error! JSON cannot be serialized due to the required property 'port' missing."
        } else {
            $Port = $JsonParameters.PSobject.Properties["port"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tls"))) {
            throw "Error! JSON cannot be serialized due to the required property 'tls' missing."
        } else {
            $Tls = $JsonParameters.PSobject.Properties["tls"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "altPorts"))) {
            throw "Error! JSON cannot be serialized due to the required property 'altPorts' missing."
        } else {
            $AltPorts = $JsonParameters.PSobject.Properties["altPorts"].value
        }

        $PSO = [PSCustomObject]@{
            "host" = ${VarHost}
            "port" = ${Port}
            "tls" = ${Tls}
            "altPorts" = ${AltPorts}
        }

        return $PSO
    }

}

