#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Test options for inbox ruleset receiving test or phone number receiving test

.PARAMETER InboxId
No description available.
.PARAMETER PhoneId
No description available.
.PARAMETER FromSender
No description available.
.OUTPUTS

TestRulesetReceivingOptions<PSCustomObject>
#>

function Initialize-TestRulesetReceivingOptions {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${InboxId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PhoneId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${FromSender}
    )

    Process {
        'Creating PSCustomObject: maislurp-client-powershell => TestRulesetReceivingOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($FromSender -eq $null) {
            throw "invalid value for 'FromSender', 'FromSender' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "inboxId" = ${InboxId}
            "phoneId" = ${PhoneId}
            "fromSender" = ${FromSender}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to TestRulesetReceivingOptions<PSCustomObject>

.DESCRIPTION

Convert from JSON to TestRulesetReceivingOptions<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

TestRulesetReceivingOptions<PSCustomObject>
#>
function ConvertFrom-JsonToTestRulesetReceivingOptions {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: maislurp-client-powershell => TestRulesetReceivingOptions' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TestRulesetReceivingOptions
        $AllProperties = ("inboxId", "phoneId", "fromSender")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'fromSender' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "fromSender"))) {
            throw "Error! JSON cannot be serialized due to the required property 'fromSender' missing."
        } else {
            $FromSender = $JsonParameters.PSobject.Properties["fromSender"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "inboxId"))) { #optional property not found
            $InboxId = $null
        } else {
            $InboxId = $JsonParameters.PSobject.Properties["inboxId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "phoneId"))) { #optional property not found
            $PhoneId = $null
        } else {
            $PhoneId = $JsonParameters.PSobject.Properties["phoneId"].value
        }

        $PSO = [PSCustomObject]@{
            "inboxId" = ${InboxId}
            "phoneId" = ${PhoneId}
            "fromSender" = ${FromSender}
        }

        return $PSO
    }

}

