#
# MailSlurp API
# MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
# Version: 6.5.2
# Contact: contact@mailslurp.dev
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'maislurp-client-powershell' -name 'CreateDevicePreviewFeedbackOptions' {
    Context 'CreateDevicePreviewFeedbackOptions' {
        It 'Initialize-CreateDevicePreviewFeedbackOptions' {
            # a simple test to create an object
            #$NewObject = Initialize-CreateDevicePreviewFeedbackOptions -Source "TEST_VALUE" -Category "TEST_VALUE" -Status "TEST_VALUE" -Rating "TEST_VALUE" -RunId "TEST_VALUE" -TargetId "TEST_VALUE" -ScreenshotId "TEST_VALUE" -Provider "TEST_VALUE" -Title "TEST_VALUE" -Comment "TEST_VALUE" -InternalNote "TEST_VALUE" -SessionId "TEST_VALUE" -LiveViewUrl "TEST_VALUE" -Metadata "TEST_VALUE"
            #$NewObject | Should -BeOfType CreateDevicePreviewFeedbackOptions
            #$NewObject.property | Should -Be 0
        }
    }
}
